### ISSUE TITLE
 Does tool support super img make package on colorOS?

### ISSUE THREAD

**Issue by skysumbra** [xiaoxindada/SGSI-build-tool#26]
Phone version not has stock rom, but has su boot.
OS: Android 11 , a only style
DD super partitions success, from unpack  tool 11. File format:data ,about 7GB
If super partitions include other img then make package again?
other img:
my_carrier
my_company
my_custom
my_engineering
my_heytap
my_manifest
my_preload
my_product
my_region
my_stock
my_version

**Comment by xiaoxindada** [comment]
Include other partition:
https://github.com/xiaoxindada/SGSI-build-tool/blob/12/makesuper.sh#L9
