### ISSUE TITLE
e2fsdroid: Invalid argument while configuring the file system

### ISSUE THREAD

**Issue by onichan0923** [xiaoxindada/SGSI-build-tool#29]
/home/onichan/SGSI-build-tool/workspace/out/config/system_file_contexts:  line 7042 has invalid file type u:object_r:rootfs:s0/system/persist
/home/onichan/SGSI-build-tool/workspace/out/config/system_file_contexts:  line 7042 has invalid file type u:object_r:rootfs:s0/system/persist
android_configure_fs: Invalid argument while opening file contexts "/home/onichan/SGSI-build-tool/workspace/out/config/system_file_contexts"
e2fsdroid: Invalid argument while configuring the file system

![截图_deepin-terminal_20220512162759](https://user-images.githubusercontent.com/68043613/168026899-b782abf1-8ddd-4b13-a558-b1bcb507af73.png)

**Comment by rahulkhatri137** [comment]
Fix contexts
It's common usual issue. 
_/system/persist_ should be a new line
