### ISSUE TITLE
imgextractor: file_contexts & fs_config errors

### ISSUE THREAD

**Issue by rahulkhatri137** [xiaoxindada/SGSI-build-tool#30]
There are error in file_contexts & fs_config files when tool extract system image which later doesn't get configured to rebuild final sgsi image.
Same errors happen everytime. I repeated the process atleast 5 times & error in same single one line. Happens mostly with OEM firmwares 

**Example**:
Following are the info in generated files about two different separate files in _system/system/etc/device_features_ -

**system_fs_config** -
_system/system/etc/device_features/peux.xml
veux.xml 0 0 0644_

**system_file_contexts** -
_/system/system/etc/device_features/peux.xml
veux.xml u:object_r:system_file:s0_

[Full system fs config and file contexts](https://github.com/rahulkhatri137/testc) *fixed ones

**Comment by xiaoxindada** [comment]
Are you using legacy MIUI patch for final build?

**Comment by xiaoxindada** [comment]
This bug exists in branch 11 
[ here ](https://github.com/xiaoxindada/SGSI-build-tool/blob/11/make/rom_make_patch/miui/make.sh#L49)

**Comment by rahulkhatri137** [comment]
> This bug exists in branch 11 [ here ](https://github.com/xiaoxindada/SGSI-build-tool/blob/11/make/rom_make_patch/miui/make.sh#L49)

Yes, I think this creates the problem. I think that implementation needs some update.

**Comment by xiaoxindada** [comment]
> > This bug exists in branch 11 [ here ](https://github.com/xiaoxindada/SGSI-build-tool/blob/11/make/rom_make_patch/miui/make.sh#L49)
> 
> Yes, I think this creates the problem. I think that implementation needs some update.

Yes, but I don't have time to update it now. You just need to change the logic here to fix it

**Comment by rahulkhatri137** [comment]
> > > This bug exists in branch 11 [ here ](https://github.com/xiaoxindada/SGSI-build-tool/blob/11/make/rom_make_patch/miui/make.sh#L49)
> > 
> > 
> > Yes, I think this creates the problem. I think that implementation needs some update.
> 
> Yes, but I don't have time to update it now. You just need to change the logic here to fix it

Here you go. Just need _for_ clause

_for xml in $xml_name; do
  echo "/system/system/etc/device_features/$xml u:object_r:system_file:s0" >> $target_contexts
  echo "system/system/etc/device_features/$xml 0 0 0644" >> $target_fs
done_

**Comment by rahulkhatri137** [comment]
Push whenever free. If want PR then I can pull one 🙂

**Comment by xiaoxindada** [comment]
> Push whenever free. If want PR then I can pull one 🙂

Can be provided the pr
