### ISSUE TITLE
不支持A-only

### ISSUE THREAD

**Issue by RedSTARO** [xiaoxindada/SGSI-build-tool#37]
编译https://hugeota.d.miui.com/V12.5.2.0.QEACNXM/miui_MI8_V12.5.2.0.QEACNXM_f5ec813d1c_10.0.zip，MIUI12.5 安卓10基于小米8的A-only显示不支持A-only，请问如何解决

**Comment by xiaoxindada** [comment]
10是可以支持的 你用错版本了
