### ISSUE TITLE
[ Bug ] failed to find - pack bug report

### ISSUE THREAD

**Issue by ghost** [xiaoxindada/SGSI-build-tool#40]
#### OS - PixelExperience (12Plus)

error reported when packing systen.img

out:
```
....... SGSI-build-tool-11/out/system -a /system ./out/system.img
loaded 6023 fs_config entries
failed to find [/system/system/etc/prop.default] in canned fs_config
```

**Comment by rahulkhatri137** [comment]
Add that file in component/add_fs/etc*

**Comment by ghost** [comment]
@rahulkhatri137 
Do you mean add this line in **SGSI-build-tool/make/add_fs/etc_fs** like this ?
```
system/system/etc/prop.default 0 0 0644
```

**Comment by rahulkhatri137** [comment]
> @rahulkhatri137 Do you mean add this line in **SGSI-build-tool/make/add_fs/etc_fs** like this ?
> 
> ```
> system/system/etc/prop.default 0 0 0644
> ```

Yes like that add in contexts too

**Comment by ghost** [comment]
> > @rahulkhatri137 Do you mean add this line in **SGSI-build-tool/make/add_fs/etc_fs** like this ?
> > ```
> > system/system/etc/prop.default 0 0 0644
> > ```
> 
> Yes like that add in contexts too

Thanks in advance. I'm doubtfully using a mistake branch for *11*. I'll try it for further bug reporting.
