### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ghost** [xiaoxindada/SGSI-build-tool#9]
SGSI-build-tool-12/12/out/system/system/system_ext/etc/build.prop: No such file or directory
PDHM00_11_OTA_0250_all_iyi66E9mjnZC.zip
Android 11

**Comment by ghost** [comment]
> SGSI-build-tool-12/12/out/system/system/system_ext/etc/build.prop: No such file or directory
> PDHM00_11_OTA_0250_all_iyi66E9mjnZC.zip  PDHM00_11_OTA_0250_all_iyi66E9mjnZC.ozip
> Android 11


E2FSPROGS_FAKE_TIME=1230768000 /media/ta/EXt4/SGSI-build-tool-12/12/tool_bin/e2fsdroid -e -T 1230768000 -S ./out/config/system_test_contexts -f /media/ta/EXt4/SGSI-build-tool-12/12/out/system -a / ./out/system.img
set_selinux_xattr: No such file or directory searching for label "/system_ext"
e2fsdroid: No such file or directory while configuring the file system


Cannot read /media/ta/EXt4/SGSI-build-tool-12/12/out/system/system/system_ext/etc/build.prop: No such file or directory

**Comment by xiaoxindada** [comment]
Please stop the garbage problem and think about it for yourself
